pr: none

jobs:
- job: build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      set -e
      docker build -t opendbc .

- job: unittests
  displayName: 'Unit tests'
  container:
    image: opendbc:latest
    options: --shm-size 1G
  dependsOn: build
  steps:
  - script: |
      docker run opendbc bash -c "python -m unittest discover opendbc"

- job: linter
  displayName: 'Python linters'
  dependsOn: build
  steps:
  - script: |
      docker run opendbc bash -c "cd opendbc/can/tests/linter_python; PYTHONPATH=/ ./flake8_opendbc.sh"
      docker run opendbc bash -c "cd opendbc/can/tests/linter_python; PYTHONPATH=/ ./pylint_opendbc.sh"
