pr: none

jobs:
- job: build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    displayName: 'Build'
  - script: |
      set -e
      docker build -t opendbc .
    displayName: 'Unit tests'
  - script: |
      docker run opendbc bash -c "python -m unittest discover opendbc"
    displayName: 'Python linter'
  - script: |
      docker run opendbc bash -c "cd opendbc/can/tests/linter_python; PYTHONPATH=/ ./flake8_opendbc.sh"
      docker run opendbc bash -c "cd opendbc/can/tests/linter_python; PYTHONPATH=/ ./pylint_opendbc.sh"
